### ISSUE TITLE
DEV-71: Avoid negative values for numeric inputs and fix typos

### ISSUE THREAD

**Issue by crismoreno** [KovDimaY/Trip-Reviewer#178]
At the moment, it is possible to enter negative numbers in the inputs of duration and expenses:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/26466644/196772379-a8945267-0002-4720-a2ab-38dadd7082e2.png">

It would be great to fix it, not letting users provide data that makes no sense anyways.

Also, there is a bunch of places in the code where you can see a typo in the word "expenses":

<img width="600" alt="image" src="https://user-images.githubusercontent.com/26466644/196772939-7677164a-8919-4306-885a-a8c979b247e2.png">

As far as I can see it does not affect UI, but still is better to remove the typo in order to keep the project nice and clean.

To work on this issue, please use a branch **DEV-71** created from **devel**. When the work is finished - create a PR to the **devel** branch. At the end of each development circles, code from the **devel** branch (if everything is ok) goes to the **master** branch and deploys to production.

**Comment by KovDimaY** [comment]
PR was merged, I am closing the issue! Great job, @crismoreno! 💪
